--Cria Contexto
USE EmpresaCJ3032221;
GO


--Define Formato Data(DIA/MES/ANO) SQL Server
SET DATEFORMAT DMY;
GO
----------------------------------------
--aula 16/03

ALTER TABLE	FUNCIONARIOS
	ADD	Telefone CHAR(10);
GO

SELECT * FROM FUNCIONARIOS;
GO

--Infos da estrutura da tabela
SELECT TABLE_CATALOG	AS 'Banco de Dados',
	   TABLE_NAME		AS 'Tabela',
	   ORDINAL_POSITION AS 'Posição',
	   COLUMN_NAME		AS 'Coluna',
	   DATA_TYPE		AS 'Tipo de Dados',
	   COLLATION_NAME	AS 'Idioma da Coluna',
	   IS_NULLABLE		AS 'Aceita Nulo?'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FUNCIONARIOS';
GO

--atualiza valor da coluna na tabela
--UPDATE [NOME TABELA] SET [ATRIBUTO] WHERE [CONDIÇÕES] GO
UPDATE FUNCIONARIOS
	SET Telefone = '3668-0010';
GO

UPDATE FUNCIONARIOS
	SET Telefone = NULL;
GO

--Atualizar um registro de uma coluna x
UPDATE FUNCIONARIOS
	SET Telefone = '3668-0010'
	WHERE ID = 1;
GO

--Atualizar varios registros
UPDATE FUNCIONARIOS SET Telefone = '3668-1550' WHERE ID = 2;
UPDATE FUNCIONARIOS	SET Telefone = '3664-5000' WHERE ID = 4;
UPDATE FUNCIONARIOS	SET Telefone = '3668-2001' WHERE ID = 5;
UPDATE FUNCIONARIOS	SET Telefone = '3663-9000' WHERE ID = 7;
UPDATE FUNCIONARIOS	SET Telefone = '3663-7000' WHERE ID = 9;
UPDATE FUNCIONARIOS	SET Telefone = '3662-1515' WHERE ID = 10;
GO

--fazer aumento com UPDATE FUNCAO YEAR ->retorna a data 
UPDATE FUNCIONARIOS
	SET Salario = Salario * 1.10
	WHERE YEAR(Admissao) < 2016;
GO

--DELETE SEM WHERE APAGA TUDO/ COM WHERE REMOVE LINHA [CONDIÇÃO]
--TRUCATE REMOVE TODAS AS LINHAS Ñ ACEITA WHERE E NAP GRAVA NO LOG

--DELETE FROM [NOME TABELA] (WHERE [CONDIÇÃO]) GO
--TRUNCATE TABLE [NOME TABELA] GO

SELECT * FROM FuncionariosCOPIA;
GO

DELETE FROM FuncionariosCOPIA
WHERE Salario < 1500;
GO

--REMOVER TUDO DE VEZ
TRUNCATE TABLE FuncionariosCOPIA;
GO

--SÓ DA PRA EXCLUIR SE NAO TIVER RESTRIÇÃO DE INTEGRIDADE (CHAVE ESTRANGEIRA)
DROP TABLE FuncionariosCOPIA;
GO

SELECT create_date AS 'Data de Criação',
	   name			AS 'Nome da Tabela'
FROM sys.tables;
GO

--OPERADORES LÓGICOS, COMPARAÇÃO, BETWEEN, LIKE, IN, EXISTS, IS NULL, IS NOT NULL
SELECT * FROM FUNCIONARIOS;
GO

--DIFERENTE DE PODE SER <> OU != OU PODE USAR {WHERE NOT [COLUNA] -> CUSTA MAIS NAO ACONSELHADO}
SELECT * FROM FUNCIONARIOS
WHERE Sexo <> 'M';
GO

SELECT * FROM FUNCIONARIOS
WHERE Sexo != 'M';
GO

SELECT * FROM FUNCIONARIOS
WHERE NOT Sexo = 'M';
GO
--CODIGOS ABAIXO SAO IGUAIS (RETORNAM A MESMA COISA)
SELECT * FROM FUNCIONARIOS
WHERE Salario >= 1000 AND
	  Salario <= 1800;
GO

SELECT * FROM FUNCIONARIOS
WHERE Salario BETWEEN 1000 AND 1800;
GO

--OPERADOR IS NULL { = NULL -> NAO FUNCIONA}
SELECT * FROM FUNCIONARIOS
WHERE	Telefone IS NULL;
GO

--IS NOT NULL
SELECT * FROM FUNCIONARIOS
WHERE	Telefone IS NOT NULL;
GO

--EXISTS
IF EXISTS (
	SELECT * FROM FUNCIONARIOS
	WHERE Salario > 2000
)
	PRINT 'Alguém recebe acima de R$ 2.000,00!';
ELSE
	PRINT 'Ninguém recebe acima de R$ 2.000,00...';
GO

--OPERADOR IN -> FUNCIONA TIPO LISTA (OR CASO NÃO HAJA IN)
SELECT * FROM FUNCIONARIOS
WHERE ID = 1 OR
	  ID = 2 OR
	  ID = 5;
GO

--COM IN
SELECT * FROM FUNCIONARIOS
WHERE ID IN (1, 2, 5);
GO

--SUB-CINSULTA
SELECT * FROM FUNCIONARIOS
WHERE Salario IN (
	SELECT Salario
	FROM FUNCIONARIOS
	WHERE Salario > 2000.00);
GO

-----------------------------------------------------------------
--Mostra Dados (TODOS) Tabela Funcionarios (pode ser feito em linha ou formatado)
SELECT * 
FROM FUNCIONARIOS;
GO